# "I pledge my honor that I have abided by the Stevens Honor System."

cs392_thread : cs392_thread.o
	gcc -pthread -o cs392_thread cs392_thread.o
cs392_thread.o : cs392_thread.c
	gcc -pthread -o cs392_thread.o -c cs392_thread.c

clean:
	rm -f *.o cs392_thread